// EDEN PARFUM - Perfume Database
const perfumesDatabase = [
    { reference: "1101", name: "Loverdose", brand: "Diesel", gender: "Women" },
    { reference: "1102", name: "Redkiss", brand: "Diesel", gender: "Women" },
    { reference: "1103", name: "Marc Jacobs Decadence", brand: "Marc Jacobs", gender: "Women" },
    { reference: "1104", name: "Marc Jacobs Perfect", brand: "Marc Jacobs", gender: "Women" },
    { reference: "1105", name: "Helena", brand: "", gender: "Women" },
    { reference: "1106", name: "Choo", brand: "Jimmy Choo", gender: "Women" },
    { reference: "1107", name: "5Th Avenue", brand: "Elisabeth Arden", gender: "Women" },
    { reference: "1108", name: "Eau Des Bienfaits", brand: "Roger Gallet", gender: "Women" },
    { reference: "1109", name: "Incidence", brand: "Yves De Sistelle", gender: "Women" },
    { reference: "1110", name: "Bulgari Jasmine Noir", brand: "Bvlgari", gender: "Women" },
    { reference: "1111", name: "Marc Jacobs Perfect Intense", brand: "Marc Jacobs", gender: "Women" },
    { reference: "1201", name: "Melle Eau Tres Belle", brand: "Azzaro", gender: "Women" },
    { reference: "1202", name: "Elle", brand: "Azzaro", gender: "Women" },
    { reference: "1204", name: "1881", brand: "Cerruti", gender: "Women" },
    { reference: "1205", name: "Crème Brûlée", brand: "", gender: "Women" },
    { reference: "1206", name: "Love", brand: "Killian", gender: "Women" },
    { reference: "1207", name: "Paradox", brand: "Prada", gender: "Women" },
    { reference: "1208", name: "Sugar", brand: "Prada", gender: "Women" },
    { reference: "1209", name: "Femme", brand: "Prada", gender: "Women" },
    { reference: "1210", name: "Paradox Intense", brand: "Prada", gender: "Women" },
    { reference: "1211", name: "Good Girl Gone Bad", brand: "Killian", gender: "Women" },
    { reference: "1212", name: "Sun Kissed Goddess", brand: "Killian", gender: "Women" },
    { reference: "1301", name: "Winter", brand: "Zara", gender: "Women" },
    { reference: "1302", name: "Nudes Bouquet", brand: "Zara", gender: "Women" },
    { reference: "1303", name: "Orchid", brand: "Zara", gender: "Women" },
    { reference: "1304", name: "Rose", brand: "Zara", gender: "Women" },
    { reference: "1305", name: "Black Amber", brand: "Zara", gender: "Women" },
    { reference: "1306", name: "Fruity", brand: "Zara", gender: "Women" },
    { reference: "1307", name: "Wonder Rose", brand: "Zara", gender: "Women" },
    { reference: "1308", name: "Peony", brand: "Zara", gender: "Women" },
    { reference: "1309", name: "Golden Decade", brand: "Zara", gender: "Women" },
    { reference: "1310", name: "Gardenia", brand: "Zara", gender: "Women" },
    { reference: "1311", name: "Cherry Smoothie", brand: "Zara", gender: "Women" },
    { reference: "1312", name: "Tropical", brand: "Zara", gender: "Women" },
    { reference: "1313", name: "Oriental", brand: "Zara", gender: "Women" },
    { reference: "1314", name: "Venice", brand: "Zara", gender: "Women" },
    { reference: "1315", name: "Femme", brand: "Zara", gender: "Women" },
    { reference: "1401", name: "Flora", brand: "Gucci", gender: "Women" },
    { reference: "1402", name: "Bloom", brand: "Gucci", gender: "Women" },
    { reference: "1403", name: "Bamboo", brand: "Gucci", gender: "Women" },
    { reference: "1404", name: "Black", brand: "Gucci", gender: "Women" },
    { reference: "1405", name: "Envy Me", brand: "Gucci", gender: "Women" },
    { reference: "1406", name: "Yellow Diamond", brand: "Versace", gender: "Women" },
    { reference: "1407", name: "Dylan Purple", brand: "Versace", gender: "Women" },
    { reference: "1408", name: "Vanitas", brand: "Versace", gender: "Women" },
    { reference: "1409", name: "Crystal Noir", brand: "Versace", gender: "Women" },
    { reference: "1410", name: "Bright Crystal", brand: "Versace", gender: "Women" },
    { reference: "1411", name: "Eros", brand: "Versace", gender: "Women" },
    { reference: "1412", name: "Bright Crystal Absolute", brand: "Versace", gender: "Women" },
    { reference: "1501", name: "Taj", brand: "Escada", gender: "Women" },
    { reference: "1502", name: "Born In Paradise", brand: "Escada", gender: "Women" },
    { reference: "1503", name: "Red Sorbet", brand: "Escada", gender: "Women" },
    { reference: "1504", name: "Cherry In The Air", brand: "Escada", gender: "Women" },
    { reference: "1505", name: "Fiesta Karioka", brand: "Escada", gender: "Women" },
    { reference: "1506", name: "Collection", brand: "Escada", gender: "Women" },
    { reference: "1507", name: "Sexy Graffiti", brand: "Escada", gender: "Women" },
    { reference: "1508", name: "Candy Love", brand: "Escada", gender: "Women" },
    { reference: "1509", name: "Show Me", brand: "Escada", gender: "Women" },
    { reference: "1510", name: "Ocean Lounge", brand: "Escada", gender: "Women" },
    { reference: "1511", name: "Brisa Cubana", brand: "Escada", gender: "Women" },
    { reference: "1601", name: "Poison", brand: "Dior", gender: "Women" },
    { reference: "1602", name: "J'Adore", brand: "Dior", gender: "Women" },
    { reference: "1603", name: "J'Adore In Joy", brand: "Dior", gender: "Women" },
    { reference: "1604", name: "Joy", brand: "Dior", gender: "Women" },
    { reference: "1605", name: "Miss Dior Cherie", brand: "Dior", gender: "Women" },
    { reference: "1606", name: "J'Adore Lumière", brand: "Dior", gender: "Women" },
    { reference: "1607", name: "Miss Dior Blooming", brand: "Dior", gender: "Women" },
    { reference: "1608", name: "Poison Girl", brand: "Dior", gender: "Women" },
    { reference: "1609", name: "Hypnotic Poison", brand: "Dior", gender: "Women" },
    { reference: "1610", name: "Belle De Jour", brand: "Dior", gender: "Women", multiplier: "x1.5" },
    { reference: "1611", name: "Sakura", brand: "Dior", gender: "Women" },
    { reference: "1612", name: "Happy Hour", brand: "Dior", gender: "Women" },
    { reference: "1613", name: "Addict", brand: "Dior", gender: "Women" },
    { reference: "1614", name: "Jadore L'Or", brand: "Dior", gender: "Women", multiplier: "x2" },
    
    // Second batch - References 2101-2910
    { reference: "2101", name: "Fantasy Midnight", brand: "Britney Spears", gender: "Women" },
    { reference: "2102", name: "Private Show", brand: "Britney Spears", gender: "Women" },
    { reference: "2103", name: "Fantasy", brand: "Britney Spears", gender: "Women" },
    { reference: "2104", name: "Paradiso", brand: "Roberto Cavalli", gender: "Women" },
    { reference: "2105", name: "Repetto", brand: "Repetto", gender: "Women" },
    { reference: "2106", name: "La Belle Fleur Terrible", brand: "Jean Paul Gaultier", gender: "Women" },
    { reference: "2107", name: "Scandal", brand: "Jean Paul Gaultier", gender: "Women" },
    { reference: "2108", name: "La Belle", brand: "Jean Paul Gaultier", gender: "Women" },
    { reference: "2109", name: "So Scandal", brand: "Jean Paul Gaultier", gender: "Women" },
    { reference: "2110", name: "Love Story", brand: "Chloe", gender: "Women" },
    { reference: "2111", name: "Chloe", brand: "Chloe", gender: "Women" },
    { reference: "2112", name: "Nomade", brand: "Chloe", gender: "Women" },
    { reference: "2113", name: "La Belle Paradise Garden", brand: "Jean Paul Gaultier", gender: "Women" },
    { reference: "2114", name: "Jean Paul Gautier Scandal Absolut -F-", brand: "Jean Paul Gaultier", gender: "Women" },
    { reference: "2201", name: "Melle", brand: "Rochas", gender: "Women" },
    { reference: "2202", name: "Girl", brand: "Rochas", gender: "Women" },
    { reference: "2203", name: "My", brand: "Burberry", gender: "Women" },
    { reference: "2204", name: "Her", brand: "Burberry", gender: "Women" },
    { reference: "2205", name: "Weekend", brand: "Burberry", gender: "Women" },
    { reference: "2206", name: "Black", brand: "Burberry", gender: "Women" },
    { reference: "2207", name: "Body", brand: "Burberry", gender: "Women" },
    { reference: "2208", name: "Her 2022", brand: "Burberry", gender: "Women" },
    { reference: "2209", name: "Her Elixir", brand: "Burberry", gender: "Women" },
    { reference: "2210", name: "Quelque Note D'Amour", brand: "Yves Rocher", gender: "Women" },
    { reference: "2211", name: "Moment De Bonheur", brand: "Yves Rocher", gender: "Women" },
    { reference: "2212", name: "So Elixir", brand: "Yves Rocher", gender: "Women" },
    { reference: "2213", name: "Plein Soleil", brand: "Yves Rocher", gender: "Women" },
    { reference: "2214", name: "Evidence", brand: "Yves Rocher", gender: "Women" },
    { reference: "2215", name: "Goddess", brand: "Burberry", gender: "Women" },
    { reference: "2216", name: "Comme Une Evidence", brand: "Yves Rocher", gender: "Women" },
    { reference: "2302", name: "Musc For Her", brand: "Narciso Rodriguez", gender: "Women" },
    { reference: "2303", name: "Poudré", brand: "Narciso Rodriguez", gender: "Women" },
    { reference: "2304", name: "Rouge", brand: "Narciso Rodriguez", gender: "Women" },
    { reference: "2305", name: "Because It'S You", brand: "Armani", gender: "Women" },
    { reference: "2306", name: "Cashmere", brand: "Armani", gender: "Women" },
    { reference: "2307", name: "Narciso Rodriguez FOR HER", brand: "Narciso Rodriguez", gender: "Women" },
    { reference: "2301", name: "My Way Floral", brand: "Armani", gender: "Women" },
    { reference: "2308", name: "My Way", brand: "Armani", gender: "Women" },
    { reference: "2309", name: "Si", brand: "Armani", gender: "Women" },
    { reference: "2310", name: "Si Passione", brand: "Armani", gender: "Women" },
    { reference: "2312", name: "L'Eau Coture", brand: "Elie Saab", gender: "Women" },
    { reference: "2313", name: "Royal", brand: "Elie Saab", gender: "Women" },
    { reference: "2314", name: "Girl Of Now", brand: "Elie Saab", gender: "Women" },
    { reference: "2315", name: "Vert Malachite", brand: "Armani", gender: "Women" },
    { reference: "2316", name: "Le Parfum", brand: "Elie Saab", gender: "Women" },
    { reference: "2401", name: "دلع البنات", brand: "", gender: "Women" },
    { reference: "2402", name: "El Jazeera", brand: "", gender: "Women" },
    { reference: "2403", name: "اميرة العرب", brand: "Lataffa", gender: "Women" },
    { reference: "2404", name: "عطر مريم", brand: "", gender: "Women" },
    { reference: "2405", name: "صبايا", brand: "Al Rehab", gender: "Women" },
    { reference: "2406", name: "مسك الطهارة", brand: "", gender: "Women" },
    { reference: "2407", name: "مسك الرمان", brand: "", gender: "Women" },
    { reference: "2408", name: "مسك التوت", brand: "", gender: "Women" },
    { reference: "2409", name: "هوس", brand: "", gender: "Women" },
    { reference: "2410", name: "رسالة", brand: "", gender: "Women" },
    { reference: "2411", name: "سحر الكلمات", brand: "", gender: "Women" },
    { reference: "2412", name: "يارا Yara", brand: "Lataffa", gender: "Women" },
    { reference: "2413", name: "Yara Candy", brand: "Lataffa", gender: "Women" },
    { reference: "2501", name: "Bare Vanilla", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2502", name: "Coconut Passion", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2503", name: "Wicked", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2504", name: "Jasmine Allure", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2505", name: "Very Sexy", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2506", name: "Bombshell Magic", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2507", name: "Bombshell Night", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2508", name: "Eau So Sexy", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2509", name: "Compassion", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2510", name: "Bombshell Holiday", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2511", name: "Smoke Oud", brand: "Kayali", gender: "Women" },
    { reference: "2512", name: "Eden Apple Juicy", brand: "Kayali", gender: "Women" },
    { reference: "2513", name: "Burning Cherry", brand: "Kayali", gender: "Women" },
    { reference: "2514", name: "Vanilla", brand: "Kayali", gender: "Women" },
    { reference: "2515", name: "Eden Sparkling Lychee", brand: "Kayali", gender: "Women" },
    { reference: "2516", name: "Very Sexy Touch", brand: "Victoria'S Secret", gender: "Women" },
    { reference: "2517", name: "Pistachio", brand: "Kayali", gender: "Women" },
    { reference: "2518", name: "Smoky Oud", brand: "Kayali", gender: "Women" },
    { reference: "2601", name: "Cloud", brand: "Ariana Grande", gender: "Women" },
    { reference: "2602", name: "Suprême Bouquet", brand: "Yves Saint Laurent", gender: "Women" },
    { reference: "2603", name: "Libre", brand: "Yves Saint Laurent", gender: "Women" },
    { reference: "2604", name: "Mon Paris", brand: "Yves Saint Laurent", gender: "Women" },
    { reference: "2605", name: "Paris", brand: "Yves Saint Laurent", gender: "Women" },
    { reference: "2606", name: "Yvress", brand: "Yves Saint Laurent", gender: "Women" },
    { reference: "2607", name: "Cinema", brand: "Yves Saint Laurent", gender: "Women" },
    { reference: "2608", name: "Manifesto", brand: "Yves Saint Laurent", gender: "Women" },
    { reference: "2609", name: "Parisienne", brand: "Yves Saint Laurent", gender: "Women" },
    { reference: "2610", name: "Black Opium", brand: "Yves Saint Laurent", gender: "Women" },
    { reference: "2611", name: "Black Opium Nuit Blanche", brand: "Yves Saint Laurent", gender: "Women" },
    { reference: "2701", name: "Elixir", brand: "Lacoste", gender: "Women" },
    { reference: "2702", name: "Legere", brand: "Lacoste", gender: "Women" },
    { reference: "2703", name: "Touch Of Pink", brand: "Lacoste", gender: "Women" },
    { reference: "2704", name: "Pineapple", brand: "Dolce&Gabbana", gender: "Women" },
    { reference: "2705", name: "Queen", brand: "Dolce&Gabbana", gender: "Women" },
    { reference: "2706", name: "Light Blue Intense", brand: "Dolce&Gabbana", gender: "Women" },
    { reference: "2707", name: "Light Blue", brand: "Dolce&Gabbana", gender: "Women" },
    { reference: "2708", name: "The One Gold", brand: "Dolce&Gabbana", gender: "Women" },
    { reference: "2709", name: "The One Desire", brand: "Dolce&Gabbana", gender: "Women" },
    { reference: "2710", name: "The Only One", brand: "Dolce&Gabbana", gender: "Women" },
    { reference: "2711", name: "The One", brand: "Dolce&Gabbana", gender: "Women" },
    { reference: "2712", name: "Rose The One", brand: "Dolce&Gabanna", gender: "Women" },
    { reference: "2713", name: "L'Impératrice", brand: "Dolce&Gabanna", gender: "Women" },
    { reference: "2714", name: "Magnetic", brand: "Lacoste", gender: "Women" },
    { reference: "2715", name: "Devotion", brand: "Dolce&Gabanna", gender: "Women" },
    { reference: "2801", name: "2006", brand: "Nina Ricci", gender: "Women" },
    { reference: "2802", name: "L'Extase", brand: "Nina Ricci", gender: "Women" },
    { reference: "2803", name: "Luna", brand: "Nina Ricci", gender: "Women" },
    { reference: "2804", name: "1E Jour", brand: "Nina Ricci", gender: "Women" },
    { reference: "2805", name: "Love", brand: "Nina Ricci", gender: "Women" },
    { reference: "2806", name: "Air Du Temps", brand: "Nina Ricci", gender: "Women" },
    { reference: "2807", name: "Sucre Noir", brand: "Arte Profumi", gender: "Women" },
    { reference: "2808", name: "Loulou", brand: "Cacharel", gender: "Women" },
    { reference: "2809", name: "Amor", brand: "Cacharel", gender: "Women" },
    { reference: "2810", name: "Anais", brand: "Cacharel", gender: "Women" },
    { reference: "2811", name: "Yes I Am", brand: "Cacharel", gender: "Women" },
    { reference: "2812", name: "Noa", brand: "Cacharel", gender: "Women" },
    { reference: "2813", name: "Promesse", brand: "Cacharel", gender: "Women" },
    { reference: "2814", name: "Eden", brand: "Cacharel", gender: "Women" },
    { reference: "2901", name: "Sun Java", brand: "Franck Olivier", gender: "Women" },
    { reference: "2902", name: "Passion", brand: "Franck Olivier", gender: "Women" },
    { reference: "2903", name: "Nature", brand: "Franck Olivier", gender: "Women" },
    { reference: "2904", name: "One Kiss", brand: "Franck Olivier", gender: "Women" },
    { reference: "2905", name: "In Pink", brand: "Franck Olivier", gender: "Women" },
    { reference: "2906", name: "Bella", brand: "Franck Olivier", gender: "Women" },
    { reference: "2907", name: "Miss", brand: "Franck Olivier", gender: "Women" },
    { reference: "2908", name: "Jardin Sur Le Nil", brand: "Hermes", gender: "Women" },
    { reference: "2909", name: "La Panthère", brand: "Cartier", gender: "Women" },
    { reference: "2910", name: "Baise Voler", brand: "Cartier", gender: "Women" },
    
    // Third batch - References 3102-3615
    { reference: "3102", name: "Lolita Land", brand: "Lolita Land", gender: "Women" },
    { reference: "3103", name: "L'Eau En Blanc", brand: "Lolita Land", gender: "Women" },
    { reference: "3104", name: "Alien", brand: "Thierry Mugler", gender: "Women", multiplier: "x2" },
    { reference: "3105", name: "Aura", brand: "Thierry Mugler", gender: "Women" },
    { reference: "3106", name: "Serpont De Bohème", brand: "Boucheron", gender: "Women" },
    { reference: "3107", name: "Oxygene", brand: "Lanvin", gender: "Women" },
    { reference: "3108", name: "Modern Princesse", brand: "Lanvin", gender: "Women" },
    { reference: "3109", name: "Eclat D'Arpège", brand: "Lanvin", gender: "Women" },
    { reference: "3110", name: "Eclat De Fleurs", brand: "Lanvin", gender: "Women" },
    { reference: "3111", name: "Alien Hypersense", brand: "Thierry Mugler", gender: "Women", multiplier: "x2" },
    { reference: "3112", name: "Cool Water Blue", brand: "Davidoff", gender: "Women" },
    { reference: "3201", name: "Hot Coture", brand: "Givenchy", gender: "Women" },
    { reference: "3202", name: "Ange Ou Demon Le Secret", brand: "Givenchy", gender: "Women" },
    { reference: "3203", name: "Play Intense", brand: "Givenchy", gender: "Women" },
    { reference: "3204", name: "Amarige", brand: "Givenchy", gender: "Women" },
    { reference: "3205", name: "Organza", brand: "Givenchy", gender: "Women" },
    { reference: "3206", name: "L'Interdit Rouge", brand: "Givenchy", gender: "Women" },
    { reference: "3207", name: "L'Interdit", brand: "Givenchy", gender: "Women" },
    { reference: "3208", name: "Very Irresistible Live", brand: "Givenchy", gender: "Women" },
    { reference: "3209", name: "Very Irresistible", brand: "Givenchy", gender: "Women" },
    { reference: "3210", name: "Irresistible", brand: "Givenchy", gender: "Women" },
    { reference: "3211", name: "Dahlia Divin L'Eau Initiale", brand: "Givenchy", gender: "Women" },
    { reference: "3212", name: "Dahlia Divin", brand: "Givenchy", gender: "Women" },
    { reference: "3301", name: "Shock Street", brand: "Calvin Klein", gender: "Women" },
    { reference: "3302", name: "Ckin2You", brand: "Calvin Klein", gender: "Women" },
    { reference: "3303", name: "Mon Guerlain", brand: "Guerlain", gender: "Women" },
    { reference: "3304", name: "La Petite Robe Noir", brand: "Guerlain", gender: "Women" },
    { reference: "3305", name: "Idylle", brand: "Guerlain", gender: "Women" },
    { reference: "3306", name: "L'Instant F", brand: "Guerlain", gender: "Women" },
    { reference: "3307", name: "Samsara", brand: "Guerlain", gender: "Women" },
    { reference: "3308", name: "Insolence", brand: "Guerlain", gender: "Women" },
    { reference: "3309", name: "Good Girl Velvet", brand: "Carolina Herrera", gender: "Women" },
    { reference: "3310", name: "212 Vip Rose Smily", brand: "Carolina Herrera", gender: "Women" },
    { reference: "3311", name: "Good Girl", brand: "Carolina Herrera", gender: "Women" },
    { reference: "3312", name: "Palmolive", brand: "", gender: "Women" },
    { reference: "3313", name: "Pas Ce Soir", brand: "Bdk", gender: "Women" },
    { reference: "3314", name: "Sense", brand: "Laverne", gender: "Women" },
    { reference: "3401", name: "Flower", brand: "Kenzo", gender: "Women" },
    { reference: "3402", name: "Flower Poppy", brand: "Kenzo", gender: "Women" },
    { reference: "3403", name: "World", brand: "Kenzo", gender: "Women" },
    { reference: "3404", name: "Idole Aura", brand: "Lancome", gender: "Women" },
    { reference: "3405", name: "Idole", brand: "Lancome", gender: "Women" },
    { reference: "3406", name: "La Vie Est Belle", brand: "Lancome", gender: "Women" },
    { reference: "3407", name: "Miracle", brand: "Lancome", gender: "Women" },
    { reference: "3408", name: "Nuit Tresor Fleur De Nuit", brand: "Lancome", gender: "Women" },
    { reference: "3409", name: "Nuit Tresor", brand: "Lancome", gender: "Women" },
    { reference: "3410", name: "Tresor Midnight Rose", brand: "Lancome", gender: "Women" },
    { reference: "3411", name: "Nuit Tresor A La Folie", brand: "Lancome", gender: "Women" },
    { reference: "3412", name: "Hypnose", brand: "Lancome", gender: "Women" },
    { reference: "3413", name: "Tresor", brand: "Lancome", gender: "Women" },
    { reference: "3414", name: "Idole Nectar", brand: "Lancome", gender: "Women" },
    { reference: "3415", name: "La Vie Est Belle Extraordinaire", brand: "Lancome", gender: "Women" },
    { reference: "3501", name: "The Scent F", brand: "Hugo Boss", gender: "Women" },
    { reference: "3502", name: "Women", brand: "Hugo Boss", gender: "Women" },
    { reference: "3503", name: "Nuit", brand: "Hugo Boss", gender: "Women" },
    { reference: "3504", name: "Jour", brand: "Hugo Boss", gender: "Women" },
    { reference: "3505", name: "Ma Vie", brand: "Hugo Boss", gender: "Women" },
    { reference: "3506", name: "Ultraviolet", brand: "Paco Rabbane", gender: "Women" },
    { reference: "3507", name: "Black Xs L'Excès", brand: "Paco Rabbane", gender: "Women" },
    { reference: "3508", name: "Fame", brand: "Paco Rabbane", gender: "Women" },
    { reference: "3509", name: "Lady Million Royal", brand: "Paco Rabbane", gender: "Women" },
    { reference: "3510", name: "Lady Million Lucky", brand: "Paco Rabbane", gender: "Women" },
    { reference: "3511", name: "Lady Million", brand: "Paco Rabbane", gender: "Women" },
    { reference: "3512", name: "Olympea", brand: "Paco Rabbane", gender: "Women" },
    { reference: "3513", name: "Strong Me", brand: "Paco Rabbane", gender: "Women" },
    { reference: "3514", name: "Women", brand: "Shalis", gender: "Women" },
    { reference: "3601", name: "Chance Eau Tendre", brand: "Chanel", gender: "Women" },
    { reference: "3602", name: "Leau Rouge N1", brand: "Chanel", gender: "Women" },
    { reference: "3603", name: "Chance Eau Vive", brand: "Chanel", gender: "Women" },
    { reference: "3604", name: "Chance", brand: "Chanel", gender: "Women" },
    { reference: "3605", name: "Allure", brand: "Chanel", gender: "Women" },
    { reference: "3606", name: "Gabrielle", brand: "Chanel", gender: "Women" },
    { reference: "3607", name: "N5", brand: "Chanel", gender: "Women" },
    { reference: "3608", name: "N19", brand: "Chanel", gender: "Women" },
    { reference: "3609", name: "Coco Mademoiselle", brand: "Chanel", gender: "Women" },
    { reference: "3610", name: "Afternoon Swim", brand: "Luis Vuitton", gender: "Mixte", multiplier: "x2" },
    { reference: "3611", name: "Contre Moi", brand: "Luis Vuitton", gender: "Mixte" },
    { reference: "3612", name: "On The Beach", brand: "Luis Vuitton", gender: "Mixte" },
    { reference: "3613", name: "Renaissance", brand: "Xerjoff", gender: "Mixte" },
    { reference: "3614", name: "Pacific Chill", brand: "Luis Vuitton", gender: "Mixte", multiplier: "x4" },
    { reference: "3615", name: "Imagination", brand: "Luis Vuitton", gender: "Mixte" },
    
    // Fourth batch - References 4101-4614
    { reference: "4101", name: "طيب الحجاز", brand: "", gender: "Mixte" },
    { reference: "4102", name: "مخلط شوكو", brand: "Al Rehab", gender: "Mixte" },
    { reference: "4103", name: "عطر دلال", brand: "Al Rehab", gender: "Mixte" },
    { reference: "4104", name: "مسك الحجرة", brand: "", gender: "Mixte" },
    { reference: "4105", name: "كراميل", brand: "", gender: "Mixte" },
    { reference: "4107", name: "وصال الذهب", brand: "", gender: "Mixte" },
    { reference: "4108", name: "عود كمبودي", brand: "", gender: "Mixte" },
    { reference: "4109", name: "عود فاخر", brand: "", gender: "Mixte" },
    { reference: "4110", name: "جواد الليل", brand: "", gender: "Mixte" },
    { reference: "4111", name: "عود شغف", brand: "", gender: "Mixte" },
    { reference: "4112", name: "طيب اليمن", brand: "", gender: "Mixte" },
    { reference: "4113", name: "أمير العود", brand: "", gender: "Mixte" },
    { reference: "4114", name: "جدور العود", brand: "", gender: "Mixte" },
    { reference: "4201", name: "Bois De Oud", brand: "Solinote", gender: "Mixte" },
    { reference: "4202", name: "Tobacco", brand: "Banafaa", gender: "Mixte" },
    { reference: "4203", name: "Oud Touch", brand: "Franck Olivier", gender: "Mixte" },
    { reference: "4204", name: "Blue Touch", brand: "Franck Olivier", gender: "Mixte" },
    { reference: "4205", name: "Tobacco Vanille", brand: "Tom Ford", gender: "Mixte" },
    { reference: "4206", name: "Lost Cherry", brand: "Tom Ford", gender: "Mixte", multiplier: "x2" },
    { reference: "4207", name: "Tobacco Oud", brand: "Tom Ford", gender: "Mixte" },
    { reference: "4208", name: "Jasmine Musc", brand: "Tom Ford", gender: "Mixte" },
    { reference: "4209", name: "Oud Vanille", brand: "Franck Olivier", gender: "Mixte" },
    { reference: "4301", name: "Oud Esfahane", brand: "Dior", gender: "Mixte" },
    { reference: "4302", name: "Kirke", brand: "Tiziana Tirenzi", gender: "Mixte" },
    { reference: "4303", name: "Al Thair", brand: "Parfums de Marly", gender: "Mixte" },
    { reference: "4304", name: "Carlisle", brand: "Parfums de Marly", gender: "Mixte" },
    { reference: "4305", name: "Orza Tiziana Tirrenzi", brand: "Tiziana Tirenzi", gender: "Mixte" },
    { reference: "4306", name: "Fluidity Gold", brand: "Kurkidjian", gender: "Mixte" },
    { reference: "4307", name: "Oud Satin Mood", brand: "Kurkidjian", gender: "Mixte", multiplier: "x2" },
    { reference: "4308", name: "Baccarat Rouge", brand: "Kurkidjian", gender: "Mixte", multiplier: "x2" },
    { reference: "4309", name: "Rose Darabie", brand: "Armani", gender: "Mixte" },
    { reference: "4310", name: "Oud", brand: "Armani", gender: "Mixte" },
    { reference: "4311", name: "Ombre Nomade", brand: "Luis Vuitton", gender: "Mixte", multiplier: "x2" },
    { reference: "4312", name: "Delina", brand: "Parfums de Marly", gender: "Mixte" },
    { reference: "4313", name: "Alexandria II", brand: "Xerjoff", gender: "Mixte" },
    { reference: "4401", name: "Oud", brand: "Roberto Cavalli", gender: "Mixte" },
    { reference: "4402", name: "Spicebomb", brand: "Viktor&Rolf", gender: "Mixte" },
    { reference: "4403", name: "Oud", brand: "Gucci", gender: "Mixte" },
    { reference: "4404", name: "Botled Oud", brand: "Hugo Boss", gender: "Mixte", multiplier: "x2" },
    { reference: "4405", name: "Supreme Oud Ralph Lauren", brand: "Polo", gender: "Mixte" },
    { reference: "4406", name: "Musc Ravageur", brand: "Frédéric Malle", gender: "Mixte" },
    { reference: "4407", name: "Share By Killian", brand: "Killian", gender: "Mixte" },
    { reference: "4408", name: "Hot Killian", brand: "Killian", gender: "Mixte" },
    { reference: "4409", name: "Naxos", brand: "Xerjoff", gender: "Mixte" },
    { reference: "4410", name: "Soft", brand: "", gender: "Mixte" },
    { reference: "4411", name: "Velvet Tendre Oud", brand: "Dolce&Gabbana", gender: "Mixte" },
    { reference: "4412", name: "N5 Amber Sensuelle", brand: "Mateu", gender: "Mixte" },
    { reference: "4413", name: "Ambre Eternelle", brand: "Guerlain", gender: "Mixte" },
    { reference: "4501", name: "Oud", brand: "Zara", gender: "Mixte" },
    { reference: "4502", name: "Black Afgano", brand: "Nasomatto", gender: "Mixte", multiplier: "x5" },
    { reference: "4503", name: "Encre Noir", brand: "La Lique", gender: "Mixte" },
    { reference: "4504", name: "Hacivat", brand: "Nishane", gender: "Mixte" },
    { reference: "4505", name: "M7 Oud Asolu", brand: "Yves Saint Laurent", gender: "Mixte" },
    { reference: "4506", name: "Almaz", brand: "Kajal", gender: "Mixte", multiplier: "x2" },
    { reference: "4601", name: "Invictus Victory Elixir", brand: "Paco Rabbane", gender: "Men" },
    { reference: "4602", name: "Ultraviolet", brand: "Paco Rabbane", gender: "Men" },
    { reference: "4603", name: "Xs Pure", brand: "Paco Rabbane", gender: "Men" },
    { reference: "4604", name: "Xs Black", brand: "Paco Rabbane", gender: "Men" },
    { reference: "4605", name: "Phantom", brand: "Paco Rabbane", gender: "Men", multiplier: "x1.5" },
    { reference: "4606", name: "Invictus", brand: "Paco Rabbane", gender: "Men" },
    { reference: "4607", name: "Invictus Victory", brand: "Paco Rabbane", gender: "Men" },
    { reference: "4608", name: "Invictus Platinium", brand: "Paco Rabbane", gender: "Men" },
    { reference: "4609", name: "1 Million", brand: "Paco Rabbane", gender: "Men" },
    { reference: "4610", name: "1 Million Royal", brand: "Paco Rabbane", gender: "Men" },
    { reference: "4611", name: "1 Million Lucky", brand: "Paco Rabbane", gender: "Men" },
    { reference: "4612", name: "1 Million Elixir", brand: "Paco Rabbane", gender: "Men" },
    
    // Fifth batch - Men's Collection References 5101-6611 + 3616
    { reference: "5101", name: "Le Beau", brand: "Jean Paul Gaultier", gender: "Men" },
    { reference: "5102", name: "Eau Du Matin", brand: "Jean Paul Gaultier", gender: "Men" },
    { reference: "5103", name: "Scandal", brand: "Jean Paul Gaultier", gender: "Men" },
    { reference: "5104", name: "Le Male", brand: "Jean Paul Gaultier", gender: "Men" },
    { reference: "5105", name: "Le Male Elixir", brand: "Jean Paul Gaultier", gender: "Men" },
    { reference: "5106", name: "Ultra Male", brand: "Jean Paul Gaultier", gender: "Men" },
    { reference: "5107", name: "Dolce&Gabbana The One", brand: "Dolce&Gabbana", gender: "Men" },
    { reference: "5108", name: "Dolce&Gabbana The One Grey", brand: "Dolce&Gabbana", gender: "Men" },
    { reference: "5109", name: "Dolce&Gabbana Layl Malaki", brand: "Dolce&Gabbana", gender: "Men" },
    { reference: "5110", name: "Dolce&Gabbana Layl Malaki V2", brand: "Dolce&Gabbana", gender: "Men" },
    { reference: "5111", name: "Dolce&Gabbana Layl Sihri", brand: "Dolce&Gabbana", gender: "Men" },
    { reference: "5112", name: "Dolce&Gabbana King", brand: "Dolce&Gabbana", gender: "Men" },
    { reference: "5113", name: "Light Blue Intense", brand: "Dolce&Gabbana", gender: "Men" },
    { reference: "5114", name: "Jean Paul Gautier Le Beau Paradise Garden", brand: "Jean Paul Gaultier", gender: "Men" },
    { reference: "5115", name: "Jean Paul Gautier Scandal Absolut -H-", brand: "Jean Paul Gaultier", gender: "Men" },
    { reference: "5116", name: "Light Blue Forever -H-", brand: "Calvin Klein", gender: "Men" },
    { reference: "5201", name: "Bois Dargent", brand: "Dior", gender: "Men" },
    { reference: "5202", name: "Gris Montain", brand: "Dior", gender: "Men" },
    { reference: "5203", name: "Colle Noir", brand: "Dior", gender: "Men" },
    { reference: "5204", name: "Ambre Nuit", brand: "Dior", gender: "Men" },
    { reference: "5205", name: "Sauvage", brand: "Dior", gender: "Men" },
    { reference: "5206", name: "Sauvage Elixir", brand: "Dior", gender: "Men" },
    { reference: "5207", name: "Eau Sauvage", brand: "Dior", gender: "Men" },
    { reference: "5208", name: "Intense", brand: "Dior", gender: "Men" },
    { reference: "5209", name: "Dior Homme Sport", brand: "Dior", gender: "Men" },
    { reference: "5210", name: "Cologne", brand: "Dior", gender: "Men" },
    { reference: "5211", name: "Fahrenheit", brand: "Dior", gender: "Men" },
    { reference: "5212", name: "Aqua Fahrenheit", brand: "Dior", gender: "Men" },
    { reference: "5301", name: "Stronger With You Oud", brand: "Armani", gender: "Men" },
    { reference: "5302", name: "Stronger With You Leather", brand: "Armani", gender: "Men" },
    { reference: "5303", name: "Stronger With You", brand: "Armani", gender: "Men" },
    { reference: "5304", name: "Aqua Di Gio", brand: "Armani", gender: "Men" },
    { reference: "5305", name: "Code", brand: "Armani", gender: "Men" },
    { reference: "5306", name: "Code Profumo", brand: "Armani", gender: "Men" },
    { reference: "5307", name: "Aqua Profondo", brand: "Armani", gender: "Men" },
    { reference: "5308", name: "Aqua Profumo", brand: "Armani", gender: "Men" },
    { reference: "5309", name: "Erba Gold", brand: "Sospiro", gender: "Men" },
    { reference: "5310", name: "Erba Pura", brand: "Sospiro", gender: "Men" },
    { reference: "5311", name: "Stronger With You Intensly", brand: "Armani", gender: "Men" },
    { reference: "5401", name: "Black Orchid", brand: "Tom Ford", gender: "Men" },
    { reference: "5402", name: "Black", brand: "Tom Ford", gender: "Men" },
    { reference: "5403", name: "Velvet Orchid", brand: "Tom Ford", gender: "Men" },
    { reference: "5404", name: "Fucking Fabulous", brand: "Tom Ford", gender: "Men" },
    { reference: "5405", name: "Kourous", brand: "Yves Saint Laurent", gender: "Men" },
    { reference: "5406", name: "Body Kourous", brand: "Yves Saint Laurent", gender: "Men" },
    { reference: "5407", name: "La Nuit De Lhomme", brand: "Yves Saint Laurent", gender: "Men" },
    { reference: "5408", name: "Ysl La Nuit De Lhomme Lelectric", brand: "Yves Saint Laurent", gender: "Men" },
    { reference: "5409", name: "Y", brand: "Yves Saint Laurent", gender: "Men" },
    { reference: "5410", name: "Lhomme Libre", brand: "Yves Saint Laurent", gender: "Men" },
    { reference: "5411", name: "Lhomme", brand: "Yves Saint Laurent", gender: "Men" },
    { reference: "5412", name: "Y Le Parfum", brand: "Yves Saint Laurent", gender: "Men" },
    { reference: "5413", name: "Myself", brand: "Yves Saint Laurent", gender: "Men" },
    { reference: "5501", name: "Eternity", brand: "Calvin Klein", gender: "Men" },
    { reference: "5502", name: "Eternity Flame", brand: "Calvin Klein", gender: "Men" },
    { reference: "5503", name: "Ck One", brand: "Calvin Klein", gender: "Men" },
    { reference: "5504", name: "The Scent", brand: "Hugo Boss", gender: "Men" },
    { reference: "5505", name: "Urban Journey", brand: "Hugo Boss", gender: "Men" },
    { reference: "5506", name: "Orange", brand: "Hugo Boss", gender: "Men" },
    { reference: "5507", name: "Botled", brand: "Hugo Boss", gender: "Men" },
    { reference: "5508", name: "Botled Intense", brand: "Hugo Boss", gender: "Men" },
    { reference: "5509", name: "Botled Marine", brand: "Hugo Boss", gender: "Men" },
    { reference: "5510", name: "Orange Charity", brand: "Hugo Boss", gender: "Men" },
    { reference: "5511", name: "Hugo", brand: "Hugo Boss", gender: "Men" },
    { reference: "5601", name: "Coco Vanille", brand: "Mancera", gender: "Men" },
    { reference: "5602", name: "Rose Vanille", brand: "Mancera", gender: "Men" },
    { reference: "5603", name: "Rose Greedy", brand: "Mancera", gender: "Men" },
    { reference: "5604", name: "Gold Intens Oud", brand: "Mancera", gender: "Men" },
    { reference: "5605", name: "Melody Of The Sun", brand: "Mancera", gender: "Men" },
    { reference: "5606", name: "Black Vanille", brand: "Mancera", gender: "Men" },
    { reference: "5607", name: "Black Gold", brand: "Mancera", gender: "Men" },
    { reference: "5608", name: "Boy", brand: "Chanel", gender: "Men" },
    { reference: "5609", name: "Allure Homme Sport", brand: "Chanel", gender: "Men" },
    { reference: "5610", name: "Alure Edition Blanche", brand: "Chanel", gender: "Men" },
    { reference: "5611", name: "Egoiste Platinium", brand: "Chanel", gender: "Men" },
    { reference: "5612", name: "Bleu", brand: "Chanel", gender: "Men" },
    { reference: "5613", name: "Antaeus", brand: "Chanel", gender: "Men" },
    { reference: "5701", name: "Classique", brand: "Azzaro", gender: "Men" },
    { reference: "5702", name: "Chrome", brand: "Azzaro", gender: "Men" },
    { reference: "5703", name: "Wanted", brand: "Azzaro", gender: "Men" },
    { reference: "5704", name: "The Most Wanted", brand: "Azzaro", gender: "Men" },
    { reference: "5705", name: "Wanted Tonic", brand: "Azzaro", gender: "Men" },
    { reference: "5706", name: "Sport", brand: "Azzaro", gender: "Men" },
    { reference: "5707", name: "Noir", brand: "Lacoste", gender: "Men" },
    { reference: "5708", name: "Blanc", brand: "Lacoste", gender: "Men" },
    { reference: "5709", name: "Bleu", brand: "Lacoste", gender: "Men" },
    { reference: "5710", name: "Lhomme Intens", brand: "Lacoste", gender: "Men" },
    { reference: "5711", name: "Booster", brand: "Lacoste", gender: "Men" },
    { reference: "5712", name: "Men", brand: "Shalis", gender: "Men" },
    { reference: "5713", name: "Original", brand: "Lacoste", gender: "Men" },
    { reference: "6101", name: "Sculpture", brand: "Nicos", gender: "Men" },
    { reference: "6102", name: "Whisky Silver", brand: "Evaflor", gender: "Men" },
    { reference: "6103", name: "Viking", brand: "Creed", gender: "Men" },
    { reference: "6104", name: "Aventus", brand: "Creed", gender: "Men" },
    { reference: "6105", name: "Bulgari", brand: "Bvlgari", gender: "Men" },
    { reference: "6106", name: "Champion", brand: "Davidoff", gender: "Men" },
    { reference: "6107", name: "Voyage", brand: "Nautica", gender: "Men" },
    { reference: "6108", name: "Rochas", brand: "Rochas", gender: "Men" },
    { reference: "6109", name: "Lapidus", brand: "Ted Lapidus", gender: "Men" },
    { reference: "6110", name: "Chairman", brand: "Yves De Sistelle", gender: "Men" },
    { reference: "6111", name: "Dalal", brand: "", gender: "Men" },
    { reference: "6201", name: "Black Scuderia", brand: "Ferrari", gender: "Men" },
    { reference: "6202", name: "Jimmy Show Men Blue", brand: "Jimmy Choo", gender: "Men" },
    { reference: "6203", name: "Declaration", brand: "Cartier", gender: "Men", multiplier: "x1.5" },
    { reference: "6204", name: "Blue Seduction", brand: "Antonio Banderas", gender: "Men" },
    { reference: "6205", name: "Tobacco", brand: "Zara", gender: "Men" },
    { reference: "6206", name: "Gold", brand: "Zara", gender: "Men" },
    { reference: "6207", name: "Vibrant Leather", brand: "Zara", gender: "Men" },
    { reference: "6208", name: "Desir For Men", brand: "Denhil", gender: "Men" },
    { reference: "6209", name: "Desir Blue", brand: "Denhil", gender: "Men" },
    { reference: "6210", name: "Leau Dessey Sport", brand: "Issey Miyake", gender: "Men" },
    { reference: "6211", name: "Leau Dessey Leau Super Majeur", brand: "Issey Miyake", gender: "Men" },
    { reference: "6301", name: "Heliotrope", brand: "Etro", gender: "Men" },
    { reference: "6302", name: "Joop Night Flight", brand: "Joop!", gender: "Men" },
    { reference: "6303", name: "Drakar Noir", brand: "Guy Laroche", gender: "Men" },
    { reference: "6304", name: "Caron", brand: "Caron", gender: "Men" },
    { reference: "6305", name: "Legend", brand: "Mont Blanc", gender: "Men" },
    { reference: "6306", name: "Happy", brand: "Clinique", gender: "Men" },
    { reference: "6307", name: "Eros", brand: "Versace", gender: "Men" },
    { reference: "6308", name: "Roma", brand: "", gender: "Men" },
    { reference: "6309", name: "Angelman", brand: "", gender: "Men" },
    { reference: "6310", name: "Night", brand: "Kenzo", gender: "Men" },
    { reference: "6311", name: "Men In Black Bulgari", brand: "Bvlgari", gender: "Men" },
    { reference: "6401", name: "Sport", brand: "Polo", gender: "Men" },
    { reference: "6402", name: "Bleu", brand: "Polo", gender: "Men" },
    { reference: "6403", name: "Ultra Bleu", brand: "Polo", gender: "Men" },
    { reference: "6404", name: "Terre d'Hermès", brand: "Hermes", gender: "Men" },


    { reference: "6405", name: "Eau De Narcisse Bleu", brand: "Hermes", gender: "Men" },
    { reference: "6406", name: "London", brand: "Burberry", gender: "Men" },
    { reference: "6407", name: "Hero", brand: "Burberry", gender: "Men" },
    { reference: "6408", name: "212 Vip Men", brand: "Carolina Herrera", gender: "Men" },
    { reference: "6409", name: "King", brand: "Carolina Herrera", gender: "Men" },
    { reference: "6410", name: "212 Men", brand: "Carolina Herrera", gender: "Men" },
    { reference: "6411", name: "Heroes", brand: "Carolina Herrera", gender: "Men" },
    { reference: "6412", name: "Mr", brand: "Burberry", gender: "Men" },
    { reference: "6501", name: "Red Legend", brand: "Mont Blanc", gender: "Men" },
    { reference: "6502", name: "Valentino", brand: "Valentino", gender: "Men" },
    { reference: "6503", name: "V", brand: "Valentino", gender: "Men" },
    { reference: "6504", name: "Vomo", brand: "Valentino", gender: "Men" },
    { reference: "6505", name: "Pi", brand: "Givenchy", gender: "Men" },
    { reference: "6506", name: "Only Gentlemen", brand: "Givenchy", gender: "Men" },
    { reference: "6507", name: "Gentlemen Society", brand: "Givenchy", gender: "Men" },
    { reference: "6508", name: "Gentlemen", brand: "Givenchy", gender: "Men" },
    { reference: "6509", name: "Play", brand: "Givenchy", gender: "Men" },
    { reference: "6510", name: "Guilty", brand: "Gucci", gender: "Men" },
    { reference: "6511", name: "Homme", brand: "Gucci", gender: "Men" },
    { reference: "6512", name: "Omo Born In Roma", brand: "Valentino", gender: "Men" },
    { reference: "6513", name: "Gentlemen Reserve Prive", brand: "Givenchy", gender: "Men" },
    { reference: "6601", name: "Eau De Passion", brand: "Franck Olivier", gender: "Men" },
    { reference: "6602", name: "Sun Java", brand: "Franck Olivier", gender: "Men" },
    { reference: "6603", name: "Sun Java White", brand: "Franck Olivier", gender: "Men" },
    { reference: "6604", name: "Iesel", brand: "Diesel", gender: "Men" },
    { reference: "6605", name: "Fuel For Life", brand: "Diesel", gender: "Men" },
    { reference: "6606", name: "Lhomme Ideal", brand: "Guerlain", gender: "Men" },
    { reference: "6607", name: "Linstant", brand: "Guerlain", gender: "Men" },
    { reference: "6608", name: "Habit Rouge", brand: "Guerlain", gender: "Men" },
    { reference: "6609", name: "1881", brand: "Cerruti", gender: "Men" },
    { reference: "6610", name: "Image", brand: "Cerruti", gender: "Men" },
    { reference: "6611", name: "Only The Brave", brand: "Diesel", gender: "Men" },
    { reference: "3616", name: "Symphony", brand: "Luis Vuitton", gender: "Mixte", multiplier: "x2" }
];

// Get unique brands for filter dropdown
function getUniqueBrands() {
    const brands = [...new Set(perfumesDatabase.map(perfume => perfume.brand).filter(brand => brand))];
    return brands.sort();
}

// Get unique genders for filter dropdown
function getUniqueGenders() {
    const genders = [...new Set(perfumesDatabase.map(perfume => perfume.gender))];
    return genders.sort();
}

// Get brand logo path
function getBrandLogo(brandName) {
    const brandLogos = {
        'Chanel': 'photos/chanel.png',
        'Yves Saint Laurent': 'photos/YSL_Logo.svg.png',
        'Luis Vuitton': 'photos/louis-vuitton-1-logo-black-and-white.png',
        'Dolce&Gabanna': 'photos/dolce_gabanna.png',
        'Burberry': 'photos/logoburberry-1400x433.png',
        'Zara': 'photos/ZARA.png',
        'Diesel': 'photos/Diesel_Parfume_Logo.png',
        'Chloe': 'photos/chloe-Converted.png'
    };
    
    return brandLogos[brandName] || null;
}
