# Railway deployment configuration
# Place this file in the backend directory for Railway deployment

[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  # Environment variables to be set in Railway dashboard:
  # SUPABASE_URL=your_supabase_project_url
  # SUPABASE_ANON_KEY=your_supabase_anon_key  
  # SUPABASE_SERVICE_ROLE_KEY=your_service_role_key
  # FRONTEND_URL=https://your-netlify-domain.netlify.app
  # NODE_ENV=production
  # PORT=3000 (automatically set by Railway)

[healthcheck]
  path = "/api/health"
  timeout = 10000
  interval = 30000