// Fragrance Data Module - Contains all fragrance image mappings and brand logo mappings
export class FragranceDataModule {
    constructor() {
        this.imageMap = null;
        this.brandLogos = null;
        this.isInitialized = false;
    }

    init() {
        if (this.isInitialized) return;
        
        this.imageMap = this.getFragranceImageMap();
        this.brandLogos = this.getBrandLogosMap();
        
        this.isInitialized = true;
    }

    getFragranceImageMap() {
        return {
            // Men's Fragrances - Fixed to match actual filenames
            '1 Million': '1 Million.avif',
            '1 Million Elixir': '1 Million Elixir.avif',
            '1 Million Lucky': '1 Million Lucky.avif',
            '1 Million Royal': '1 Million Royal.avif',
            '1881': '1881.avif',
            '212 Men': '212 Men.avif',
            '212 Vip Men': '212 Vip Men.avif',
            'Allure Homme Sport': 'Allure Homme Sport.avif',
            'Antaeus': 'Antaeus.avif',
            'Aqua Di Gio': 'Aqua Di Gio.avif',
            'Aqua Fahrenheit': 'Aqua Fahrenheit.avif',
            'Aqua Profondo': 'Aqua Profondo.avif',
            'Aqua Profumo': 'Aqua Profumo.avif',
            'Aventus': 'Aventus.avif',
            'Black Afgano': 'Black Afgano.avif',
            'Black Gold': 'Black Gold.avif',
            'Black Orchid': 'Black Orchid.avif',
            'Black Tom Ford': 'Black tom ford.avif',
            'Black Vanille': 'Black Vanille.avif',
            'Blanc': 'Blanc.avif',
            'Bleu Lacoste': 'Bleu lacoste.avif',
            'Bleu': 'Bleu.avif',
            'Bleu Polo': 'Bleu polo.avif',
            'Blue Seduction': 'Blue Seduction.avif',
            'Blue Touch': 'Blue Touch.avif',
            'Bois Dargent': 'Bois Dargent.avif',
            'Bois De Oud': 'Bois De Oud.avif',
            'Body Kouros': 'Body kouros.avif',
            'Body Kourous': 'Body kouros.avif',
            'Booster': 'Booster.avif',
            'Botled': 'Botled.avif',
            'Botled Intense': 'Botled Intense.avif',
            'Botled Marine': 'Botled Marine.avif',
            'Botled Oud': 'Botled Oud.avif',
            'Boy': 'Boy.avif',
            'Bulgari': 'Bulgari.avif',
            'Caron': 'Caron.avif',
            'Chairman': 'Chairman.avif',
            'Champion': 'Champion.avif',
            'Chrome': 'Chrome.avif',
            'Ck One': 'Ck One.avif',
            'Classique': 'Classique.avif',
            'Code': 'Code.avif',
            'Code Profumo': 'Code Profumo.avif',
            'Cologne': 'Cologne.avif',
            'Colle Noir': 'Colle Noir.avif',
            'Declaration': 'Declaration.avif',
            'Desir Blue': 'Desir Blue.avif',
            'Desir For Men': 'Desir For Men.avif',
            'Diesel Iesel': 'diesel iesel.avif',
            'Iesel': 'diesel iesel.avif',
            'Dior Homme Sport': 'Dior Homme Sport.avif',
            'Dolce&Gabbana King': 'Dolce&Gabbana King.avif',
            'Dolce&Gabbana Layl Malaki': 'Dolce&Gabbana Layl Malaki.avif',
            'Dolce&Gabbana Layl Malaki V2': 'Dolce&Gabbana Layl Malaki v2.avif',
            'Dolce&Gabbana Layl Sihri': 'Dolce&Gabbana Layl Sihri.avif',
            'Dolce&Gabbana Light Blue Intense': 'Dolce&Gabbana Light Blue Intense.avif',
            'Dolce&Gabbana The One': 'Dolce&Gabbana The One.avif',
            'Dolce&Gabbana The One Grey': 'Dolce&Gabbana The One Grey.avif',
            'Drakar Noir': 'Drakar Noir.avif',
            'Eau De Narcisse Bleu': 'Eau De Narcisse Bleu.avif',
            'Eau De Passion': 'Eau De Passion.avif',
            'Eau Du Matin': 'Eau Du Matin.avif',
            'Eau Sauvage': 'Eau Sauvage.avif',
            'Egoiste Platinium': 'Egoiste Platinium.avif',
            'Encre Noir': 'Encre Noir.avif',
            'Erba Gold': 'Erba Gold.avif',
            'Erba Pura': 'Erba Pura.avif',
            'Eros Men': 'Eros.avif',
            'Eternity': 'Eternity.avif',
            'Eternity Flame': 'Eternity Flame.avif',
            'Fahrenheit': 'Fahrenheit.avif',
            'Fucking Fabulous': 'Fucking Fabulous.avif',
            'Fuel For Life': 'Fuel for life.avif',
            'Gentlemen': 'Gentlemen.avif',
            'Gentlemen Reserve Prive': 'Gentlemen Reserve Prive.avif',
            'Gentlemen Society': 'Gentlemen Society.avif',
            'Gold': 'Gold.avif',
            'Gold Intens Oud': 'Gold Intens Oud.avif',
            'Gris Montain': 'Gris Montain.avif',
            'Gucci Oud': 'gucci oud.avif',
            'Guilty': 'Guilty.avif',
            'Habit Rouge': 'Habit Rouge.avif',
            'Hacivat': 'Nishane.avif',
            'Happy': 'Happy.avif',
            'Helena': 'helena.avif',
            'Heliotrope': 'Heliotrope.avif',
            'Hero': 'Hero.avif',
            'Heroes': 'Heroes.avif',
            'Homme': 'Homme.avif',
            'Hugo': 'Hugo.avif',
            'Image': 'Image.avif',
            'Intense': 'Intense.avif',
            'Invictus': 'Invictus.avif',
            'Invictus Platinium': 'Invictus Platinium.avif',
            'Invictus Victory': 'Invictus Victory.avif',
            'Invictus Victory Elixir': 'Invictus Victory Elixir.avif',
            'Jean Paul Gautier Le Beau Paradise Garden': 'Jean Paul Gautier Le Beau Paradise Garden.avif',
            'Jean Paul Gautier Scandal Absolut -H-': 'Jean Paul Gautier Scandal Absolut -H-.avif',
            'Jimmy Show Men Blue': 'Jimmy Show Men Blue.avif',
            'Joop Night Flight': 'Joop Night Flight.avif',
            'King': 'King.avif',
            'Kourous': 'Kourous.avif',
            'La Nuit De Lhomme': 'La Nuit De Lhomme.avif',
            'Lapidus': 'Lapidus.avif',
            'Le Beau': 'Le Beau.avif',
            'Le Male': 'Le Male.avif',
            'Le Male Elixir': 'Le Male Elixir.avif',
            'Leau Dessey Leau Super Majeur': 'Leau Dessey Leau Super Majeur.avif',
            'Leau Dessey Sport': 'Leau Dessey Sport.avif',
            'Legend': 'Legend.avif',
            'Lhomme': 'Lhomme.avif',
            'Lhomme Ideal': 'Lhomme Ideal.avif',
            'Lhomme Intens': 'Lhomme Intens.avif',
            'Lhomme Libre': 'Lhomme Libre.avif',
            'Light Blue Forever -H-': 'Light blue forever -h-.avif',
            'Linstant': 'Linstant.avif',
            'London': 'London.avif',
            'Lost Cherry': 'Lost Cherry.avif',
            'M7 Oud Asolu': 'M7 Oud Asolu.avif',
            'Men': 'Men.avif',
            'Men In Black Bulgari': 'Men In Black Bulgari.avif',
            'Mr Burberry': 'Mr burberry.avif',
            'Mr': 'Mr burberry.avif',
            'Myself': 'Myself.avif',
            'Night': 'Night.avif',
            'Noir': 'Noir.avif',
            'Omo Born In Roma': 'Omo Born In Roma.avif',
            'Only Gentlemen': 'Only Gentlemen.avif',
            'Only The Brave': 'Only The Brave.avif',
            'Orange': 'Orange.avif',
            'Orange Charity': 'Orange Charity.avif',
            'Original': 'Original.avif',
            'Oud': 'Oud.avif',
            'Oud Esfahane': 'Oud Esfahane.avif',
            'Oud Satin Mood': 'Oud Satin Mood.avif',
            'Oud Touch': 'Oud Touch.avif',
            'Oud Vanille': 'Oud Vanille.avif',
            'Phantom': 'Phantom.avif',
            'Pi': 'Pi.avif',
            'Play': 'Play.avif',
            'Red Legend': 'Red Legend.avif',
            'Roberto Cavalli Oud': 'Roberto Cavalli Oud.avif',
            'Rochas': 'Rochas.avif',
            'Rose Greedy': 'Rose Greedy.avif',
            'Rose Vanille': 'Rose Vanille.avif',
            'Sauvage': 'Sauvage.avif',
            'Sauvage Elixir': 'Sauvage Elixir.avif',
            'Scandal Homme': 'Scandal homme.avif',
            'Sculpture': 'Sculpture.avif',
            'Spicebomb': 'Spicebomb.avif',
            'Sport': 'Sport.avif',
            'Sport Polo': 'Sport polo.avif',
            'Stronger With You Intensly': 'Stronger With You Intensly.avif',
            'Stronger With You Leather': 'Stronger With You Leather.avif',
            'Stronger With You Oud': 'Stronger With You Oud.avif',
            'Sun Java White': 'Sun Java White.avif',
            'Supreme Oud Ralph Lauren': 'Supreme Oud Ralph Lauren.avif',
            'Terre Dhermes': 'Terre dhermes.avif',
            "Terre d'Hermès": 'Terre dhermes.avif',
            'The Most Wanted': 'The Most Wanted.avif',
            'The Scent': 'The Scent.avif',
            'Tobacco': 'Tobacco.avif',
            'Tobacco Oud': 'Tobacco Oud.avif',
            'Tobacco Vanille': 'Tobacco Vanille.avif',
            'Ultra Bleu': 'Ultra Bleu.avif',
            'Ultra Male': 'Ultra Male.avif',
            'Ultraviolet Men': 'Ultraviolet men.avif',
            'Urban Journey': 'urban journey.avif',
            'V Valentino': 'V valentino.avif',
            'V': 'V valentino.avif',
            'Valentino': 'V valentino.avif',
            'Velvet Orchid': 'Velvet Orchid.avif',
            'Velvet Tendre Oud': 'Velvet Tendre Oud.avif',
            'Vibrant Leather': 'Vibrant Leather.avif',
            'Viking': 'Viking.avif',
            'Vomo': 'Vomo.avif',
            'Voyage': 'Voyage.avif',
            'Wanted': 'Wanted.avif',
            'Wanted Tonic': 'Wanted Tonic.avif',
            'Whisky Silver': 'Whisky Silver.avif',
            'Y': 'Y.avif',
            'Y Le Parfum': 'Y Le Parfum.avif',
            'Ysl La Nuit De Lhomme Lelectric': 'Ysl La Nuit De Lhomme Lelectric.avif',
            
            // Women's Fragrances - Fixed to match actual files
            '2006': '2006.avif',
            '212 Vip Rose Smily': '212 Vip Rose Smily.avif',
            '375x500.6341.2x': '375x500.6341.2x.avif',
            '5Th Avenue': '5th avenue.avif',
            'Addict': 'Addict.avif',
            'Afternoon Swim': 'Afternoon Swim.avif',
            'Ageur F.Malles': 'Ageur F.Malles.avif',
            'Musc Ravageur': 'Ageur F.Malles.avif',
            'Air Du Temps': 'Air Du Temps.avif',
            'Al Thair': 'Al Thair.avif',
            'Alexendria Ii': 'Alexendria Ii.avif',
            'Alexandria II': 'Alexendria Ii.avif',
            'Alien': 'Alien.avif',
            'Alien Hypersense': 'Alien Hypersense.avif',
            'Allure': 'Allure.avif',
            'Allure Edition Blanche': 'Alure Edition Blanche.avif',
            'Alure Edition Blanche': 'Alure Edition Blanche.avif',
            'Almaz': 'Almaz.avif',
            'Amarige': 'Amarige.avif',
            'Ambre Eternelle': 'Ambre Eternelle.avif',
            'Ambre Nuit': 'Ambre Nuit.avif',
            'Ameerat Al Arab': 'Ameerat Al Arab.avif',
            'Ameerat Al Arab Rose': 'Ameerat Al Arab Rose.avif',
            'اميرة العرب': 'Ameerat Al Arab.avif',
            'Amor': 'Amor.avif',
            'Anais': 'Anais.avif',
            'Ange Ou Demon Le Secret': 'Ange Ou Demon Le Secret.avif',
            'Armani Prive Vert Malachite': 'Armani Prive Vert Malachite.avif',
            'Vert Malachite': 'Armani Prive Vert Malachite.avif',
            'Aura': 'Aura.avif',
            'Elle': 'Azzaro elle.avif',
            'Baccarat Rouge': 'Baccarat Rouge.avif',
            'Baise Voler': 'Baise Voler.avif',
            'Bamboo': 'Bamoboo gucci.avif',
            'Bamoboo': 'Bamoboo gucci.avif',
            'Bare Vanilla': 'Bare vanila.avif',
            'Because It\'S You': 'Because It\'S You.avif',
            'Bella': 'Bella.avif',
            'Belle De Jour': 'Belle De Jour.avif',
            'Black Amber': 'Black Amber.avif',
            'Black': 'Black burberry.avif',
            'Black Opium': 'Black Opium.avif',
            'Black Opium Nuit Blanche': 'Black Opium Nuit Blanche.avif',
            'Black Scuderia': 'Black Scuderia.avif',
            'Black Xs L\'Excès': 'Black Xs L\'Excès.avif',
            'Body': 'Body.avif',
            'Bombshell Holiday': 'Boombshell holdiay.avif',
            'Bombshell Magic': 'Bombshell magic.avif',
            'Bombshell Night': 'Bombshell Night.avif',
            'Born In Paradise': 'Born In Paradise.avif',
            'Bright Crystal': 'Bright Cristal.avif',
            'Bright Cristal': 'Bright Cristal.avif',
            'Bright Crystal Absolute': 'Bright Cristal Absolut.avif',
            'Bright Cristal Absolut': 'Bright Cristal Absolut.avif',
            'Brisa Cubana': 'Brisa Cubana.avif',
            'Bloom': 'gucci Bloom.avif',
            'Bulgari Jasmine Noir': 'Bulgari Jasmine Noir.avif',
            'Burnina Cherry': 'Burning Cherry.avif',
            'Burning Cherry': 'Burning Cherry.avif',
            'Candy Love': 'Candy Love.avif',
            'Carlisle Marly': 'Carlisle marly.avif',
            'Carlisle': 'Carlisle marly.avif',
            'Cashmere': 'Cashmer.avif',
            'Cashmer': 'Cashmer.avif',
            'Chance': 'Chance.avif',
            'Chance Eau Tendre': 'Chance Eau Tendre.avif',
            'Chance Eau Vive': 'Chance Eau Vive.avif',
            'Cherry In The Air': 'Cherry In The Air.avif',
            'Cherry Smoothie': 'Cherry Smothie.avif',
            'Cherry Smothie': 'Cherry Smothie.avif',
            'Chloe': 'Chloe.avif',
            'Cinema': 'Cinema.avif',
            'Ckin2You': 'Ckin2You.avif',
            'Cloud': 'Cloud.avif',
            'Coco Melle': 'Coco Melle.avif',
            'Coco Mademoiselle': 'Coco Melle.avif',
            'Coco Vanille': 'Coco Vanille.avif',
            'Coconut Passion': 'Coconut Passion.avif',
            'Collection': 'Collection escada.avif',
            'Comme Une Evidence': 'Comme Une Evidence.avif',
            'Compassion': 'Compassion.avif',
            'Contre Moi': 'Contre Moi.avif',
            'Cool Water Blue': 'Cool Water Blue.avif',
            'Crème Brûlée': 'Creme Bruller.avif',
            'Creme Bruller': 'Creme Bruller.avif',
            'Crystal Noir': 'Cristal Noir.avif',
            'Cristal Noir': 'Cristal Noir.avif',
            'Dahlia Divin': 'Dahlia Divin.avif',
            'Dahlia Divin L\'Eau Initiale': 'Dahlia Divin L\'Eau Initiale.avif',
            'Dalal': 'Dalal.avif',
            'Marc Jacobs Decadence': 'decadence.avif',
            'Decadence': 'decadence.avif',
            'Delina': 'Delina.avif',
            'Devotion': 'Devotion.avif',
            'Dylan Purple': 'Dylan Purple.avif',
            'Eau Des Bienfaits': 'Eau Des Bienfaits.avif',
            'Eau So Sexy': 'Eau so sexy.avif',
            'Eclat D\'Arpège': 'Eclat D\'Arpège.avif',
            'Eclat De Fleurs': 'Eclat De Fleurs.avif',
            'Eden': 'Eden cacharel.avif',
            'Eden Apple Jucy': 'Eden Juicy Apple.avif',
            'Eden Apple Juicy': 'Eden Juicy Apple.avif',
            'Eden Juicy Apple': 'Eden Juicy Apple.avif',
            'Eden Sparkling Leccy': 'Eden Sparkling Lychee.avif',
            'Eden Sparkling Lychee': 'Eden Sparkling Lychee.avif',
            'El Jazeera': 'el jazeera.jpg',
            'Elixir': 'Elixir lacoste.avif',
            'Envy Me': 'Envy Me.avif',
            'Eros': 'Eros Versace.avif',
            'Evidence': 'Evidence.avif',
            'Fame': 'Fame.avif',
            'Fantasy': 'Fantasy.avif',
            'Fiesta Karioka': 'Fiesta Karioka.avif',
            'Flora': 'gucci flora.avif',
            'Flower': 'Flower.avif',
            'Flower Poppy': 'Flower Poppy.avif',
            'Fluidity Gold': 'Fluidity Gold.avif',
            'Fruity': 'Fruite zara.avif',
            'Fruite': 'Fruite zara.avif',
            'Gabrielle': 'Gabrielle.avif',
            'Gardenia': 'Gardenia.avif',
            'Girl Of Now': 'Girl of Now Elie Saab.avif',
            'Girl': 'Girl rochas.avif',
            'Godess': 'Goddess.avif',
            'Goddess': 'Goddess.avif',
            'Golden Decade': 'Golden Decade.avif',
            'Good Girl': 'Good Girl.avif',
            'Good Girl Gone Bad': 'Good Girl Gone Bad.avif',
            'Good Girl Velvet': 'Good Girl Velvet.avif',
            'Gucci Black': 'gucci black.avif',
            'Guilty Black': 'gucci black.avif',
            'Happy Hour': 'Happy Hour.avif',
            'Her': 'Her burberry.avif',
            'Her 2022': 'Her 2022.avif',
            'Her Elixir': 'Her Elixir.avif',
            'Hot Coture': 'Hot Coture.avif',
            'Hot Killian': 'Hot Killian.avif',
            'Hypnose': 'Hypnose.avif',
            'Hypnotic Poison': 'Hypnotic Poison.avif',
            'Idole': 'Idole.avif',
            'Idole Aura': 'Idole Aura.avif',
            'Idole Nectar': 'Idole Nectar.avif',
            'Idylle': 'Idylle.avif',
            'Imagination': 'Imagination.avif',
            'In Pink': 'In Pink.avif',
            'Incidence': 'Incidence.avif',
            'Insolence': 'Insolence.avif',
            'Irresistible': 'Irresistible.avif',
            'J\'Adore': 'J\'Adore.avif',
            'J\'Adore In Joy': 'J\'Adore In Joy.avif',
            'J\'Adore Lumière': 'J\'Adore Lumière.avif',
            'J\'adore L\'Or': 'J\'adore L\'Or.avif',
            'Jadore L\'Or': 'J\'adore L\'Or.avif',
            'Jardin Sur Le Nil': 'Jardin Sur Le Nil.avif',
            'Jasmine Allure': 'Jasmine Allure.avif',
            'Jasmine Musc': 'Jasmine Musc.avif',
            'Jean Paul Gautier Scandal Absolut -F-': 'Jean Paul Gautier Scandal Absolut -F-.avif',
            'Choo': 'jimmy choo.avif',
            'Jour': 'Jour.avif',
            'Joy': 'Joy.avif',
            'Kirke': 'Kirke.avif',
            'L\'Eau Coture': 'L\'Eau Couture Elie Saab.avif',
            'L\'Extase': 'L\'Extase.avif',
            'L\'Impératrice': 'L\'Impératrice.avif',
            'L\'Instant F': 'L\'Instant F.avif',
            'L\'Interdit': 'L\'Interdit.avif',
            'L\'Interdit Rouge': 'L\'Interdit Rouge.avif',
            'La Belle': 'La Belle.avif',
            'La Belle Fleur Terrible': 'La Belle Fleur Terrible.avif',
            'La Belle Paradise Garden': 'La Belle Paradise Garden.avif',
            'La Petite Robe Noir': 'La Petite Robe Noir.avif',
            'La Vie Est Belle': 'La Vie Est Belle.avif',
            'La Vie Est Belle Extraordinaire': 'La Vie Est Belle Extraordinaire.avif',
            'Lady Million': 'Lady Million.avif',
            'Lady Million Lucky': 'Lady Million Lucky.avif',
            'Lady Million Royal': 'Lady Million Royal.avif',
            'Leau Rouge N1': 'Leau Rouge N1.avif',
            'Le Parfum': 'Le Parfum Elie Saab.avif',
            'Royal': 'Le Parfum Royal Elie Saab.avif',
            'Legere': 'Legere.avif',
            'Libre': 'Libre.avif',
            'Light Blue': 'Light Blue women.avif',
            'Light Blue Intense': 'Light Blue Intense women.avif',
            'Lolita Land': 'Lolita Land.avif',
            'Loulou': 'Loulou.avif',
            'Love Story': 'Love Story.avif',
            'Loverdose': 'loverdose.avif',
            'Luna': 'Luna.avif',
            'Luna Blossom': 'LUNA BLOSSOM.avif',
            'Ma Vie': 'Ma Vie.avif',
            'Mademoiselle': 'Mademoiselle Rochas.avif',
            'Melle': 'Mademoiselle Rochas.avif',
            'Magnetic': 'Magnetic lacoste women.avif',
            'Manifesto': 'Manifesto.avif',
            'Marc Jacobs Perfect Intense': 'Marc Jacobs Perfect Intense.avif',
            'Melle Eau Tres Belle': 'Melle Eau Tres Belle.avif',
            'Melody Of The Sun': 'Melody Of The Sun.avif',
            'Fantasy Midnight': 'Midnight Fantasy.avif',
            'Midnight Fantasy': 'Midnight Fantasy.avif',
            'Miracle': 'Miracle.avif',
            'Miss': 'Miss.avif',
            'Miss Dior Blooming': 'Miss Dior Blooming.avif',
            'Miss Dior Cherie': 'Miss Dior Cherie.avif',
            'Modern Princesse': 'Modern Princesse.avif',
            'Moment De Bonheur': 'Moment De Bonheur.avif',
            'Mon Guerlain': 'Mon Guerlain.avif',
            'Mon Paris': 'Mon Paris.avif',
            'Musc For Her': 'Musc for her.avif',
            'My': 'My Burberry.avif',
            'My Burberry': 'My Burberry.avif',
            'My Way': 'My Way.avif',
            'My Way Floral': 'My Way Floral.avif',
            'N19': 'N19.avif',
            'N5': 'N5.avif',
            'N5 Amber Sensuelle': 'N5 Amber Sensuelle.avif',
            'Narciso For Her': 'Narciso for her.avif',
            'Narciso Rodriguez FOR HER': 'Narciso for her.avif',
            'Nature': 'Nature.avif',
            'Naxos': 'Naxos.avif',
            'Nishane': 'Nishane.avif',
            'Noa': 'Noa.avif',
            'Nomade': 'Nomade.avif',
            'Nudes Bouquet': 'Nudes Bouquet.avif',
            'Nuit': 'Nuit.avif',
            'Nuit Tresor': 'Nuit Tresor.avif',
            'Nuit Tresor A La Folie': 'Nuit Tresor A La Folie.avif',
            'Nuit Tresor Fleur De Nuit': 'Nuit Tresor Fleur De Nuit.avif',
            'Ocean Lounge': 'Ocean Lounge.avif',
            'Olympea': 'Olympea.avif',
            'Ombre Nomade': 'Ombre Nomade.avif',
            'On The Beach': 'On The Beach.avif',
            'One Kiss': 'One Kiss.avif',
            'Orchid': 'Orchid.avif',
            'Organza': 'Organza.avif',
            'Orza Tiziana Tirrenzi': 'Orza Tiziana Tirrenzi.avif',
            'Oxygene': 'Oxygene.avif',
            'Pacific Chill': 'Pacific Chill.avif',
            'Paradiso': 'Paradiso.avif',
            'Paradox': 'Paradox prada.avif',
            'Paradox Intens': 'Paradox Intens.avif',
            'Paradox Intense': 'Paradox Intens.avif',
            'Paris': 'Paris.avif',
            'Parisienne': 'Parisienne.avif',
            'Pas Ce Soir': 'Pas Ce Soir.avif',
            'Passion': 'Passion.avif',
            'Peony': 'Peony zara.avif',
            'Perfect': 'perfect.avif',
            'Pineapple': 'Pineapple.avif',
            'Pistachio': 'Pisrachio.avif',
            'Pisrachio': 'Pisrachio.avif',
            'Play Intens': 'Play Intens.webp',
            'Play Intense': 'Play Intens.webp',
            'Plein Soleil': 'Plein Soleil.avif',
            'Poison': 'Poison dior.avif',
            'Poison Girl': 'Poison Girl.avif',
            'Poudré': 'Poudré.avif',
            'Femme': 'prada femme.avif',
            'Premier Jour Nina Ricci for women': 'Premier Jour Nina Ricci for women.avif',
            '1E Jour': 'Premier Jour Nina Ricci for women.avif',
            'Private Show': 'privet show.avif',
            'Privet Show': 'privet show.avif',
            'Promesse': 'Promesse.avif',
            'Queen': 'queen.avif',
            'Quelque Note D\'Amour': 'Quelque Note D\'Amour.avif',
            'Red Srobet': 'Red sorbet.avif',
            'Red Sorbet': 'Red sorbet.avif',
            'Redkiss': 'redkiss.avif',
            'Renaissance': 'Renaissance.avif',
            'Repetto': 'Repetto.avif',
            'Rose': 'Rose zara.avif',
            'Rose The One': 'Rose The One.avif',
            'Rose Darabie': 'Rose Darabie.avif',
            'Rouge': 'Rouge narciso.avif',
            'Sabaya': 'Sabaya.avif',
            'صبايا': 'Sabaya.avif',
            'Sakura': 'Sakura.avif',
            'Samsara': 'Samsara.avif',
            'Scandal': 'Scandal.avif',
            'Serpont De Bohème': 'Serpont De Bohème.avif',
            'Sense': 'verne.avif',
            'Sexy Graffiti': 'Sexy Graffiti.avif',
            'Shalis Women': 'shalis women.avif',
            'Share By Killian': 'Share By Killian.avif',
            'Shock Street': 'Shock Street.avif',
            'Show Me': 'Show Me.avif',
            'Si': 'Si.avif',
            'Si Passione': 'Si passione.avif',
            'Smoke Oud': 'Smoky Oud.avif',
            'Smoky Oud': 'Smoky Oud.avif',
            'So Elixir': 'So Elixir.avif',
            'So Scandal': 'So Scandal.avif',
            'Soft': 'Soft.avif',
            'Stronger With You': 'Stronger With You.avif',
            'Sucre Noir': 'Sucre Noir.avif',
            'Sugar': 'Sugar prada.avif',
            'Sun Java': 'Sun Java women.avif',
            'Sun Kissed Goddess': 'Sun Kissed Godess.avif',
            'Sun Kissed Godess': 'Sun Kissed Godess.avif',
            'Suprême Bouquet': 'Suprême Bouquet.avif',
            'Symphony': 'symphony.avif',
            'Taj': 'Taj.avif',
            'The One': 'The One for women.avif',
            'The One Desire': 'The One Desir.avif',
            'The One Desir': 'The One Desir.avif',
            'The One Gold': 'The One Gold.avif',
            'The Only One': 'The Only One.avif',
            'The Scent F': 'The Scent F.avif',
            'Touch Of Pink': 'Touch Of Pink.avif',
            'Tresor': 'Tresor.avif',
            'Tresor Midnight Rose': 'Tresor Midnight Rose.avif',
            'Ultraviolet': 'Ultraviolet.avif',
            'Vanilla': 'Vanilla kayali.avif',
            'Vanitas': 'Vanitas.avif',
            'Venice': 'Venice.avif',
            'Verne': 'verne.avif',
            'Very Irresistible': 'Very Irresistible.avif',
            'Very Irresistible Live': 'Very Irresistible Live.avif',
            'Very Sexy': 'Very sexy.avif',
            'Very Sexy Touch': 'Very Sexy Touch.avif',
            'Weekend': 'Weekend burberry.avif',
            'Wicked': 'Wicked.avif',
            'Winter': 'Winter zara.avif',
            'Women': 'Women.avif',
            'Wonder Rose': 'Wonder Rose zara.avif',
            'World': 'World.avif',
            'Xs Black': 'Xs Black.avif',
            'Xs Pure': 'Xs Pure.avif',
            'Yara': 'Yara.avif',
            'Yara Candy': 'Yara Candy.avif',
            'يارا Yara': 'Yara.avif',
            'Yellow Diamond': 'Yellow Diamond.avif',
            'Yes I Am': 'Yes I Am.avif',
            'Yvress': 'Yvress.avif',
            'Oriental': 'zara Oriental.avif',
            'Tropical': 'zara Tropical.avif',
            
            // Arabic Fragrances
            'رسالة': 'رسالة.avif',
            'دلع البنات': 'دلع البنات.jpg',
            'سحر الكلمات': 'سحر الكلمات.webp',
            'طيب الحجاز': 'طيب الحجاز.jpg',
            'طيب اليمن': 'طيب الحجاز.jpg',
            'عطر دلال': 'عطر دلال.webp',
            'عطر مريم': 'عطر مريم.webp',
            'عود شغف': 'عود شغف.webp',
            'عود فاخر': 'عود فاخر.webp',
            'عود كمبودي': 'عود كمبودي.webp',
            'كراميل': 'كراميل.jpg',
            'مخلط شوكو': 'مخلط شوكو.webp',
            'مسك التوت': 'مسك التوت.jpeg',
            'مسك الحجرة': 'مسك الحجرة.jpg',
            'مسك الرمان': 'مسك الرمان.png',
            'مسك الطهارة': 'مسك-الطهارة-.jpg',
            'هوس': 'هوس.avif',
            'وصال الذهب': 'وصال الذهب.webp',
            'أمير العود': 'أمير العود.webp',
            'جدور العود': 'جدور العود.jpg',
            'جواد الليل': 'جواد الليل.jpg',
            
            // Additional name variations and mappings
            'Strong Me': 'Strong Me.avif',
            'Marly': 'Carlisle marly.avif',
            'Tom Ford Black': 'Black tom ford.avif'
        };
    }

    getBrandLogosMap() {
        return {
            'Al Rehab': 'photos/al rehab.png',
            'Antonio Banderas': 'photos/Antonio Banderas.jpg',
            'Ariana Grande': 'photos/Ariana Grande.jpg',
            'Giorgio Armani': 'photos/armani.png',
            'Arte Profumi': 'photos/Arte Profumi.jpg',
            'Banafaa': 'photos/Banafaa.jpg',
            'BDK Parfums': 'photos/Bdk.webp',
            'Britney Spears': 'photos/Britney_Spears.png',
            'Bulgari': 'photos/Bulgari_logo.svg.png',
            'Burberry': 'photos/BURBERRY.svg',
            'Cacharel': 'photos/Cacharel.jpg',
            'Calvin Klein': 'photos/calvin klein.svg',
            'Carolina Herrera': 'photos/Carolina Herrera.png',
            'Caron': 'photos/Caron.jpg',
            'Cartier': 'photos/Cartier.png',
            'Cerruti': 'photos/Cerruti.svg',
            'Chanel': 'photos/chanel.png',
            'Chloe': 'photos/chloe-Converted.png',
            'Clinique': 'photos/Clinique.png',
            'Creed': 'photos/creed.png',
            'Davidoff': 'photos/Davidoff.svg',
            'Dior': 'photos/dior.png',
            'Dolce & Gabbana': 'photos/Dolce-Gabbana-logo-emblem.jpg',
            'GUESS': 'photos/guess-1-logo-black-and-white.png',
            'Givenchy': 'photos/givenchy-logo-png-5.png',
            'Gucci': 'photos/gucci-1-logo-black-and-white.png',
            'Hugo Boss': 'photos/hugo boss.png',
            'Jean Paul Gaultier': 'photos/jean-paul-gaultier-logo.jpg',
            'Kenzo': 'photos/61fd47dd1042bd46515add61_logo (1) kenzo.png',
            'Killian': 'photos/killian_perfume_brand_logo_final.png',
            'Lacoste': 'photos/lacoste-logo.svg',
            'Lancôme': 'photos/lancome_logo_by_juliuslove-d6q4qcv.png',
            'Louis Vuitton': 'photos/louis-vuitton-1-logo-black-and-white.png',
            'Maison Francis Kurkdjian': 'photos/maison_francis_kurkdjian.png',
            'Mont Blanc': 'photos/mont blanc.png',
            'Montale': 'photos/montale-logo.png',
            'Narciso Rodriguez': 'photos/narciso-rodriguez-seeklogo.com.svg',
            'Nishane': 'photos/nishane_brand_logo_final.png',
            'Paco Rabanne': 'photos/paco-rabanne-logo.jpg',
            'Prada': 'photos/prada-1-logo-black-and-white.png',
            'Ralph Lauren': 'photos/ralph-lauren-4-logo-black-and-white.png',
            'Roberto Cavalli': 'photos/roberto-cavalli-logo.svg',
            'Rochas': 'photos/rochas-logo.png',
            'Shalis': 'photos/Shalis.png'
        };
    }

    getFragranceImage(perfume) {
        if (!this.isInitialized) this.init();
        
        let imageName = this.imageMap[perfume.name];
        
        if (!imageName) {
            const lowerName = perfume.name.toLowerCase();
            for (const [key, value] of Object.entries(this.imageMap)) {
                if (key.toLowerCase() === lowerName) {
                    imageName = value;
                    break;
                }
            }
        }
        
        if (!imageName) {
            return 'placeholder.avif';
        }
        
        return `photos/${imageName}`;
    }

    getBrandLogo(brand) {
        if (!this.isInitialized) this.init();
        
        return this.brandLogos[brand] || null;
    }

    // Search for fragrance names that contain the query
    searchFragrances(query) {
        if (!this.isInitialized) this.init();
        
        const normalizedQuery = query.toLowerCase();
        const matches = [];
        
        for (const [name, image] of Object.entries(this.imageMap)) {
            if (name.toLowerCase().includes(normalizedQuery)) {
                matches.push({ name, image });
            }
        }
        
        return matches;
    }

    // Get all available fragrance names
    getAllFragranceNames() {
        if (!this.isInitialized) this.init();
        
        return Object.keys(this.imageMap);
    }

    // Get all available brand names
    getAllBrandNames() {
        if (!this.isInitialized) this.init();
        
        return Object.keys(this.brandLogos);
    }
}

// Export utility functions for backwards compatibility
export function getFragranceImage(perfume) {
    const dataModule = new FragranceDataModule();
    return dataModule.getFragranceImage(perfume);
}

export function getBrandLogo(brand) {
    const dataModule = new FragranceDataModule();
    return dataModule.getBrandLogo(brand);
}